### PR TITLE
Change custom-user-schema-uri value to urn:scim:wso2:schema

### PR DESCRIPTION
**Pull request by ravindudsilva**
Change custom-user-schema-uri value from "urn:scim:custom:schema' to  "urn:scim:wso2:schema"

### CODE REVIEW

**Comment by piraveena** [comment]
can we change the default value from here as well? https://github.com/wso2/charon/blob/master/modules/charon-core/src/main/java/org/wso2/charon3/core/schema/SCIMConstants.java#L28. If the config is not available, then it will fallback to this value.

**Comment by emswbandara** [comment]
need to update here as well
https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/master/features/org.wso2.carbon.identity.scim2.common.feature/resources/org.wso2.carbon.identity.scim2.common.feature.default.json#L4

**Review by IsuraD — APPROVED** [review]

**Review by IsuraD — CHANGES_REQUESTED** [review]
Need to update other pointed places as well.

**Comment by ravindudsilva** [comment]
> need to update here as well
> https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/blob/master/features/org.wso2.carbon.identity.scim2.common.feature/resources/org.wso2.carbon.identity.scim2.common.feature.default.json#L4

Added in commit 0411eb1507c30d83d062cda0293489a3397a6ade

**Comment by ravindudsilva** [comment]
> change the default value



> can we change the default value from here as well? https://github.com/wso2/charon/blob/master/modules/charon-core/src/main/java/org/wso2/charon3/core/schema/SCIMConstants.java#L28. If the config from the file is not available, then it will fallback to this default value in code.

PR - https://github.com/wso2/charon/pull/349

**Review by emswbandara — APPROVED** [review]

**Review by IsuraD — APPROVED** [review]

**Comment by AnuradhaSK** [comment]
Fixes integration test failures by https://github.com/wso2/product-is/pull/12012

**Pull request merged**
